apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: trains-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-service
        image: ghcr.io/mreider/proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DT_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dynatrace-otel-secrets
              key: DT_ENDPOINT
        - name: DT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace-otel-secrets
              key: DT_API_TOKEN
