apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: trains-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6
        imagePullPolicy: Always
        command: ["redis-server", "--requirepass", "password"]
        ports:
        - containerPort: 6379
