apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: trains-demo
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
      - name: ticket-service
        image: ghcr.io/mreider/ticket_service:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: DT_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dynatrace-otel-secrets
              key: DT_ENDPOINT
        - name: DT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace-otel-secrets
              key: DT_API_TOKEN
